{-} Copyright 2018 Allison Wong
 -  This project is licensed under the MIT license.  Full terms can be found at:
 -  https://github.com/wonal/Book-Mapper/blob/master/LICENSE.
 -  The code in this file was generated from the Yesod-Simple Stack template and is not modified.
 -  The template can be generated by the command: stack new <project name> yesod-simple.
 -  The Yesod framework is licensed under the MIT license, and further information can be found at:
 -  https://github.com/yesodweb/yesod/blob/master/LICENSE.  
 -}

{-# LANGUAGE PackageImports #-}
import "BookMapper" Application (develMain)
import Prelude (IO)

main :: IO ()
main = develMain
